stages:
    - runSCAScanUsingSnyk

run-sca-job:
    stage: runSCAScanUsingSnyk
    image: maven:3.8.5-openjdk-17-slim
    script: |
      SNYK_TOKEN='2f14ae96-ea4f-4dd0-b761-17593b32cad8'
      export SNYK_TOKEN
      mvn snyk:test -fn